### PR TITLE
add dist option to cli

### PR DESCRIPTION
**Pull request by dorayx**
Add a new option `dist` to output the transformed files to the specified directory.

### CODE REVIEW

**Comment by walkerrandolphsmith** [comment]
Is this on the road map? I can pick it back up if so.

**Comment by boopathi** [comment]
It's not on my roadmap now. I think it's a good to have option. Feel free to send a PR 😃

**Comment by walkerrandolphsmith** [comment]
Taking

**Comment by boopathi** [comment]
Closing this as inactive. Feel free to send PR with latest 2.x changes in master. Thanks!

**Comment by walkerrandolphsmith** [comment]
Sorry for the false hope. This was pushed down my priority list to the point where I even forgot to give the community the heads up I could not uphold my commitment. Again apologies.

**Pull request closed without merging**
