### PR TITLE
fix(react-svg-core): prevent arrow function output with extra plugin

### PR DESCRIPTION
**Pull request by peter-mouland**
## issue

The output has an arrow function in it.  This PR adds a new babel plugin to remove the arrow function from the output.

## setup

When using rollup with the following config: 

```js
const svgPlugin = require('rollup-plugin-react-svg');
...
svgPlugin({
     svgo: {
          plugins: [{ convertShapeToPath: false }, { cleanupIDs: false }],
     },
}),
```

## Code examples

To test it was react-svg-loader rather than my own setup, I have checked the output of non-svg code.

*non-svg example:*

```js
// source
const test = () => { return 'test'; };

// output
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var test = function test() {
  return 'test';
};

```

*svg example:*

```js
// source
import Svg from './svg.svg';
console.log(Svg);

// output
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
var Svg = ((_ref) => {
  let props = _objectWithoutProperties(_ref, ["styles"]);

  return React.createElement(
    "svg",
    _extends({ xmlns: "http://www.w3.org/2000/svg", width: "512", height: "512", viewBox: "0 0 512 512" }, props),
    React.createElement("path", { d: "M258.4 247.6c26.8 0 48.5-21.7 48.5-48.5s-22-48-49-48-48 21.4-48 48 21.5 48.7 48.3 48.7zm0-84.6c20 0 36 16 36 36s-16 36.2-36 36.2-36-16.2-36-36 16-36.2 36-36.2z" })
  );
});

console.log(Svg);
```

## Output with PR

```js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
var Svg = (function (_ref) {
  let props = _objectWithoutProperties(_ref, ["styles"]);

  return React.createElement(
        "svg",
  _extends({ xmlns: "http://www.w3.org/2000/svg", width: "512", height: "512", viewBox: "0 0 512 512" }, props),
  React.createElement("path", { d: "M258.4 247.6c26.8 0 48.5-21.7 48.5-48.5s-22-48-49-48-48 21.4-48 48 21.5 48.7 48.3 48.7zm0-84.6c20 0 36 16 36 36s-16 36.2-36 36.2-36-16.2-36-36 16-36.2 36-36.2z" })
);
});

  console.log(Svg);

```

### CODE REVIEW

**Comment by boopathi** [comment]
closing it as outdated. please comment to reopen

**Comment by peter-mouland** [comment]
how is this outdated, has it now been fixed?

**Comment by boopathi** [comment]
you can pass the output of react-svg-loader to babel-loader and convert arrow functions to functions using that plugin.

**Comment by peter-mouland** [comment]
@boopathi the latest release looks like late last year, sorry to be a pain, but is a new release needed or is what you describe documented somewhere I can take a look?

**Comment by boopathi** [comment]
An example to use babel-loader on top of react-svg-loader - https://github.com/boopathi/react-svg-loader/tree/master/packages/react-svg-loader#loader-output 

Also, you can check webpack docs https://webpack.js.org/concepts/loaders#using-loaders - to combine multiple loaders.

**Comment by MrSeaWave** [comment]
but if I use rollup ,how can i to set it to prevent arrow function ?

**Comment by lastnigtic** [comment]
> but if I use rollup-plugin-react-svg ,how can i to set it to prevent arrow function ?

same here

**Comment by lastnigtic** [comment]
> > but if I use rollup-plugin-react-svg ,how can i to set it to prevent arrow function ?
> 
> same here

if somebody using rollup-plugin-react-svg with typescript. You can set `include` option in typescript  compile plugin to get the svg file compiled

**Pull request closed without merging**
