### PR TITLE
Ignore all local babel config

### LINKED ISSUE #263: building error - 'no filename was passed to Babel'
It's a last version 3.0.1

```
ERROR in ./src/img/deal.svg
Module build failed (from ../node_modules/react-svg-loader/lib/loader.js):
Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel
    at matchPattern (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:431:11)
    at /Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:418:35
    at Array.some (<anonymous>)
    at matchesPatterns (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:418:19)
    at shouldIgnore (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:404:17)
    at /Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:272:11
    at Array.some (<anonymous>)
    at /Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:267:26
    at buildRootChain (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/config-chain.js:90:20)
    at loadPrivatePartialConfig (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/partial.js:85:55)
    at loadFullConfig (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/config/full.js:43:39)
    at transformSync (/Users/avshamshurin/workspace/filebar/node_modules/@babel/core/lib/transform.js:41:38)
    at /Users/avshamshurin/workspace/filebar/node_modules/react-svg-core/lib/index.js:30:45
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### PR DESCRIPTION
**Pull request by liamcmitchell-sc**
Fixes #263

### CODE REVIEW

**Comment by alex-shamshurin** [comment]
Has a version with this PR already published ?

**Comment by liamcmitchell-sc** [comment]
3.0.2 was released after this was merged but it doesn't look like this change was included. Maybe it was published without running the build step.

**Comment by alex-shamshurin** [comment]
Yep, this was not published.

**Comment by boopathi** [comment]
Oh. Oops. must be a glitch. I'll publish it again today.

**Comment by alex-shamshurin** [comment]
We are still waiting for release)) Sorry.

**Comment by liamcmitchell-sc** [comment]
3.0.3 was released 14 hours ago: https://www.npmjs.com/package/react-svg-loader
Works for me, thanks @boopathi

**Pull request merged**
